# fly.toml app configuration file generated for milb-watcher on 2025-04-26T11:45:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'milb-watcher'
primary_region = 'mia'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'

[[mounts]]
  source = 'milb_logs'
  destination = '/app/logs'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
